In [1]:
import numpy as np
import pandas as pd

In [2]:
data= pd.read_csv(r"C:\Users\Ashwini Shetty\Desktop\PyGWalker - Python Data Visualization tool  Streamlit Integration\Mumbai House Prices.csv", delimiter=",", low_memory=True)
data.head(70)

,bhk,type,locality,area,price,price_unit,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New
...,...,...,...,...,...,...,...,...,...
65,1,Apartment,Godrej Urban Park,450,1.39,Cr,Powai,Under Construction,New
66,3,Apartment,Aurum Q Island R4 AND R5,1259,2.80,Cr,Ghansoli,Ready to move,New
67,2,Apartment,Raymond Raymond Realty TenX Habitat,515,1.24,Cr,Thane West,Under Construction,New
68,3,Apartment,Asshna Seabliss,1274,4.20,Cr,Andheri West,Under Construction,New
69,2,Apartment,Mayfair The View,582,1.49,Cr,Vikhroli,Under Construction,New

In [3]:
data.shape

(76038, 9)

In [4]:
data.isnull().sum()

bhk           0
type          0
locality      0
area          0
price         0
price_unit    0
region        0
status        0
age           0
dtype: int64

In [5]:
# Remove duplicate rows
data = data.drop_duplicates()

# Reset index after removing duplicates
data.reset_index(drop=True, inplace=True)

In [6]:
data.shape

(55726, 9)

In [7]:
data.head(30)

,bhk,type,locality,area,price,price_unit,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New
5,2,Apartment,Bhoomi Simana Wing A Phase 1,826,3.30,Cr,Parel,Under Construction,New
6,5,Villa,Agami Estancia,2921,1.99,Cr,Boisar,Under Construction,New
7,3,Apartment,Sanghvi Infenia,778,2.89,Cr,Santacruz East,Under Construction,New
8,1,Apartment,Shubh Shreeji Heights,396,29.84,L,Badlapur East,Ready to move,New
9,2,Apartment,Aplite Greenstone Heritage,671,2.72,Cr,Fort,Under Construction,New
10,1,Studio Apartment,A Plus Golden Corner,502,16.56,L,Badlapur West,Under Construction,New
11,2,Apartment,Unimont Imperia,950,41.75,L,Khopoli,Under Construction,New
12,3,Apartment,Aayush Gulmohar,753,1.77,Cr,Chembur,Under Construction,New
13,2,Apartment,Roswalt Zaiden,605,1.55,Cr,Jogeshwari West,Under Construction,New
14,1,Apartment,Angel Falcon Emerald Dunlin,557,58.50,L,Vasai,Under Construction,New
15,2,Apartment,Proviso Sai Proviso Icon Greater Kharghar Road...,635,83.00,L,Kalamboli,Under Construction,New
16,1,Apartment,Godrej Urban Park,450,1.39,Cr,Powai,Under Construction,New
17,3,Apartment,Aurum Q Island R4 AND R5,1259,2.80,Cr,Ghansoli,Ready to move,New
18,2,Apartment,Raymond Raymond Realty TenX Habitat,555,1.42,Cr,Thane West,Under Construction,New
19,3,Apartment,Asshna Seabliss,1274,4.20,Cr,Andheri West,Under Construction,New
20,2,Apartment,Mayfair The View,582,1.49,Cr,Vikhroli,Under Construction,New
21,1,Apartment,Shakti Shree Siddhivinayak II,483,37.52,L,Bhiwandi,Under Construction,New
22,1,Apartment,Vardhan Heights,320,69.90,L,Chembur,Under Construction,New
23,1,Apartment,Puraniks Unicorn Phase 1,396,42.99,L,Thane West,Under Construction,New
24,2,Apartment,Pyramid Elements,638,1.26,Cr,Airoli,Under Construction,New
25,2,Apartment,Tharwani Meghna Montana,1047,49.58,L,Ambernath West,Under Construction,New
26,2,Apartment,Dev Drashti Empire Phase 1,1080,57.24,L,Bhiwandi,Ready to move,New
27,2,Apartment,B G Shirke Monte Verita West Tower,555,1.31,Cr,Borivali East,Under Construction,New
28,1,Apartment,Jindal Avenue,261,47.50,L,Panvel,Under Construction,New
29,2,Apartment,Walekar Homes,594,34.50,L,Ambernath West,Ready to move,New

In [8]:
data["price_unit"].unique()

array(['Cr', 'L'], dtype=object)

In [9]:
data["price_unit"]=data["price_unit"].replace({"Cr":10000000,"L":100000})

In [10]:
data["price_unit"].unique()

array([10000000,   100000], dtype=int64)

In [11]:
# Perform element-wise multiplication of the columns
data['price'] = data['price'] * data['price_unit']

# If you want to keep only the merged column and drop the original columns, you can do:
data.drop(['price_unit'], axis=1, inplace=True)

In [12]:
data.head(10)

,bhk,type,locality,area,price,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,25000000.0,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,5251000.0,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,17300000.0,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,5998000.0,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,9411000.0,Mira Road East,Under Construction,New
5,2,Apartment,Bhoomi Simana Wing A Phase 1,826,33000000.0,Parel,Under Construction,New
6,5,Villa,Agami Estancia,2921,19900000.0,Boisar,Under Construction,New
7,3,Apartment,Sanghvi Infenia,778,28900000.0,Santacruz East,Under Construction,New
8,1,Apartment,Shubh Shreeji Heights,396,2984000.0,Badlapur East,Ready to move,New
9,2,Apartment,Aplite Greenstone Heritage,671,27200000.0,Fort,Under Construction,New

In [13]:
data.to_excel("ddd.xlsx",index=False)